cache:
    paths:
    - node_modules/

stages:
- build
- deploy


Deploy review:
    image: lahautesociete/basic:3
    stage: deploy
    except:
    - preproduction
    - production
    environment:
        name: review/$CI_BUILD_REF_SLUG
        url: http://preprod.lahautesociete.com/lahautesociete/grid-tool/$CI_BUILD_REF_SLUG/www/
        on_stop: stop_review
    script:
    - yarn
    - npm run build
    - node_modules/.bin/deployator deploy --config deployment.js --environment=review --branch="$CI_BUILD_REF_SLUG" --synchronize


stop_review:
    image: lahautesociete/basic:3
    stage: deploy
    script:
    - yarn
    - node_modules/.bin/deployator remove --config deployment.js --environment=review --branch="$CI_BUILD_REF_SLUG"
    when: manual
    except:
    - preproduction
    - production
    environment:
        name: review/$CI_BUILD_REF_SLUG
        action: stop

Deploy preproduction:
    image: lahautesociete/basic:3
    stage: deploy
    only:
    - preproduction
    environment:
        name: review/$CI_BUILD_REF_SLUG
        url: http://preprod.lahautesociete.com/lahautesociete/grid-tool/$CI_BUILD_REF_SLUG/www/
    script:
    - yarn
    - npm run build
    - node_modules/.bin/deployator deploy --config deployment.js --environment=preproduction --synchronize
